// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/proto/registry/v1/registry.proto

package registryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Weight        int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Datacenter    string                 `protobuf:"bytes,7,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Namespace     string                 `protobuf:"bytes,9,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group         string                 `protobuf:"bytes,10,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInstance) Reset() {
	*x = ServiceInstance{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInstance) ProtoMessage() {}

func (x *ServiceInstance) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInstance.ProtoReflect.Descriptor instead.
func (*ServiceInstance) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceInstance) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceInstance) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServiceInstance) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceInstance) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ServiceInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceInstance) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

func (x *ServiceInstance) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ServiceInstance) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceInstance) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *ServiceInstance       `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetInstance() *ServiceInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group         string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DeregisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeregisterRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeregisterRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *DeregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetInstanceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "online" or "offline"
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInstanceStatusRequest) Reset() {
	*x = SetInstanceStatusRequest{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInstanceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInstanceStatusRequest) ProtoMessage() {}

func (x *SetInstanceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInstanceStatusRequest.ProtoReflect.Descriptor instead.
func (*SetInstanceStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *SetInstanceStatusRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SetInstanceStatusRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SetInstanceStatusRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SetInstanceStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SetInstanceStatusRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type SetInstanceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInstanceStatusResponse) Reset() {
	*x = SetInstanceStatusResponse{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInstanceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInstanceStatusResponse) ProtoMessage() {}

func (x *SetInstanceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInstanceStatusResponse.ProtoReflect.Descriptor instead.
func (*SetInstanceStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{6}
}

func (x *SetInstanceStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group         string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HeartbeatRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *HeartbeatRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	HealthyOnly   bool                   `protobuf:"varint,2,opt,name=healthy_only,json=healthyOnly,proto3" json:"healthy_only,omitempty"`
	Datacenter    string                 `protobuf:"bytes,3,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{9}
}

func (x *DiscoverRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DiscoverRequest) GetHealthyOnly() bool {
	if x != nil {
		return x.HealthyOnly
	}
	return false
}

func (x *DiscoverRequest) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

func (x *DiscoverRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DiscoverRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type DiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*ServiceInstance     `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{10}
}

func (x *DiscoverResponse) GetInstances() []*ServiceInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{11}
}

func (x *WatchRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *WatchRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WatchRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "update", "offline", "online"
	Instances     []*ServiceInstance     `protobuf:"bytes,2,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{12}
}

func (x *WatchResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *WatchResponse) GetInstances() []*ServiceInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type GetMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersRequest) Reset() {
	*x = GetMembersRequest{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersRequest) ProtoMessage() {}

func (x *GetMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersRequest.ProtoReflect.Descriptor instead.
func (*GetMembersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{13}
}

type ClusterMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	IsLocal       bool                   `protobuf:"varint,5,opt,name=is_local,json=isLocal,proto3" json:"is_local,omitempty"`
	HttpAddr      string                 `protobuf:"bytes,6,opt,name=http_addr,json=httpAddr,proto3" json:"http_addr,omitempty"`
	GrpcAddr      string                 `protobuf:"bytes,7,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"`
	QuicAddr      string                 `protobuf:"bytes,8,opt,name=quic_addr,json=quicAddr,proto3" json:"quic_addr,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,9,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMember) Reset() {
	*x = ClusterMember{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMember) ProtoMessage() {}

func (x *ClusterMember) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMember.ProtoReflect.Descriptor instead.
func (*ClusterMember) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{14}
}

func (x *ClusterMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterMember) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClusterMember) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClusterMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ClusterMember) GetIsLocal() bool {
	if x != nil {
		return x.IsLocal
	}
	return false
}

func (x *ClusterMember) GetHttpAddr() string {
	if x != nil {
		return x.HttpAddr
	}
	return ""
}

func (x *ClusterMember) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

func (x *ClusterMember) GetQuicAddr() string {
	if x != nil {
		return x.QuicAddr
	}
	return ""
}

func (x *ClusterMember) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

type GetMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*ClusterMember       `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersResponse) Reset() {
	*x = GetMembersResponse{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersResponse) ProtoMessage() {}

func (x *GetMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersResponse.ProtoReflect.Descriptor instead.
func (*GetMembersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{15}
}

func (x *GetMembersResponse) GetMembers() []*ClusterMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type ReportTopologyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespace       string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ConsumerService string                 `protobuf:"bytes,2,opt,name=consumer_service,json=consumerService,proto3" json:"consumer_service,omitempty"`
	Providers       []string               `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`
	Checksum        string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportTopologyRequest) Reset() {
	*x = ReportTopologyRequest{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTopologyRequest) ProtoMessage() {}

func (x *ReportTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTopologyRequest.ProtoReflect.Descriptor instead.
func (*ReportTopologyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{16}
}

func (x *ReportTopologyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ReportTopologyRequest) GetConsumerService() string {
	if x != nil {
		return x.ConsumerService
	}
	return ""
}

func (x *ReportTopologyRequest) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *ReportTopologyRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type ReportTopologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Changed       bool                   `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTopologyResponse) Reset() {
	*x = ReportTopologyResponse{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTopologyResponse) ProtoMessage() {}

func (x *ReportTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTopologyResponse.ProtoReflect.Descriptor instead.
func (*ReportTopologyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{17}
}

func (x *ReportTopologyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportTopologyResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

var File_api_proto_registry_v1_registry_proto protoreflect.FileDescriptor

const file_api_proto_registry_v1_registry_proto_rawDesc = "" +
	"\n" +
	"$api/proto/registry/v1/registry.proto\x12\x0fsdk.registry.v1\"\xf9\x02\n" +
	"\x0fServiceInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"datacenter\x18\a \x01(\tR\n" +
	"datacenter\x12J\n" +
	"\bmetadata\x18\b \x03(\v2..sdk.registry.v1.ServiceInstance.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\tnamespace\x18\t \x01(\tR\tnamespace\x12\x14\n" +
	"\x05group\x18\n" +
	" \x01(\tR\x05group\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x0fRegisterRequest\x12<\n" +
	"\binstance\x18\x01 \x01(\v2 .sdk.registry.v1.ServiceInstanceR\binstance\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8b\x01\n" +
	"\x11DeregisterRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\".\n" +
	"\x12DeregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xaa\x01\n" +
	"\x18SetInstanceStatusRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\"5\n" +
	"\x19SetInstanceStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8a\x01\n" +
	"\x10HeartbeatRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xab\x01\n" +
	"\x0fDiscoverRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12!\n" +
	"\fhealthy_only\x18\x02 \x01(\bR\vhealthyOnly\x12\x1e\n" +
	"\n" +
	"datacenter\x18\x03 \x01(\tR\n" +
	"datacenter\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\"R\n" +
	"\x10DiscoverResponse\x12>\n" +
	"\tinstances\x18\x01 \x03(\v2 .sdk.registry.v1.ServiceInstanceR\tinstances\"e\n" +
	"\fWatchRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\"g\n" +
	"\rWatchResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12>\n" +
	"\tinstances\x18\x02 \x03(\v2 .sdk.registry.v1.ServiceInstanceR\tinstances\"\x13\n" +
	"\x11GetMembersRequest\"\xf4\x01\n" +
	"\rClusterMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x19\n" +
	"\bis_local\x18\x05 \x01(\bR\aisLocal\x12\x1b\n" +
	"\thttp_addr\x18\x06 \x01(\tR\bhttpAddr\x12\x1b\n" +
	"\tgrpc_addr\x18\a \x01(\tR\bgrpcAddr\x12\x1b\n" +
	"\tquic_addr\x18\b \x01(\tR\bquicAddr\x12\x1b\n" +
	"\traft_addr\x18\t \x01(\tR\braftAddr\"N\n" +
	"\x12GetMembersResponse\x128\n" +
	"\amembers\x18\x01 \x03(\v2\x1e.sdk.registry.v1.ClusterMemberR\amembers\"\x9a\x01\n" +
	"\x15ReportTopologyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12)\n" +
	"\x10consumer_service\x18\x02 \x01(\tR\x0fconsumerService\x12\x1c\n" +
	"\tproviders\x18\x03 \x03(\tR\tproviders\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\"L\n" +
	"\x16ReportTopologyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\achanged\x18\x02 \x01(\bR\achanged2\xce\x05\n" +
	"\x0fRegistryService\x12O\n" +
	"\bRegister\x12 .sdk.registry.v1.RegisterRequest\x1a!.sdk.registry.v1.RegisterResponse\x12U\n" +
	"\n" +
	"Deregister\x12\".sdk.registry.v1.DeregisterRequest\x1a#.sdk.registry.v1.DeregisterResponse\x12j\n" +
	"\x11SetInstanceStatus\x12).sdk.registry.v1.SetInstanceStatusRequest\x1a*.sdk.registry.v1.SetInstanceStatusResponse\x12R\n" +
	"\tHeartbeat\x12!.sdk.registry.v1.HeartbeatRequest\x1a\".sdk.registry.v1.HeartbeatResponse\x12O\n" +
	"\bDiscover\x12 .sdk.registry.v1.DiscoverRequest\x1a!.sdk.registry.v1.DiscoverResponse\x12H\n" +
	"\x05Watch\x12\x1d.sdk.registry.v1.WatchRequest\x1a\x1e.sdk.registry.v1.WatchResponse0\x01\x12U\n" +
	"\n" +
	"GetMembers\x12\".sdk.registry.v1.GetMembersRequest\x1a#.sdk.registry.v1.GetMembersResponse\x12a\n" +
	"\x0eReportTopology\x12&.sdk.registry.v1.ReportTopologyRequest\x1a'.sdk.registry.v1.ReportTopologyResponseBKZIgithub.com/shiyindaxiaojie/eden-registry/api/proto/registry/v1;registryv1b\x06proto3"

var (
	file_api_proto_registry_v1_registry_proto_rawDescOnce sync.Once
	file_api_proto_registry_v1_registry_proto_rawDescData []byte
)

func file_api_proto_registry_v1_registry_proto_rawDescGZIP() []byte {
	file_api_proto_registry_v1_registry_proto_rawDescOnce.Do(func() {
		file_api_proto_registry_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_registry_v1_registry_proto_rawDesc), len(file_api_proto_registry_v1_registry_proto_rawDesc)))
	})
	return file_api_proto_registry_v1_registry_proto_rawDescData
}

var file_api_proto_registry_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_proto_registry_v1_registry_proto_goTypes = []any{
	(*ServiceInstance)(nil),           // 0: sdk.registry.v1.ServiceInstance
	(*RegisterRequest)(nil),           // 1: sdk.registry.v1.RegisterRequest
	(*RegisterResponse)(nil),          // 2: sdk.registry.v1.RegisterResponse
	(*DeregisterRequest)(nil),         // 3: sdk.registry.v1.DeregisterRequest
	(*DeregisterResponse)(nil),        // 4: sdk.registry.v1.DeregisterResponse
	(*SetInstanceStatusRequest)(nil),  // 5: sdk.registry.v1.SetInstanceStatusRequest
	(*SetInstanceStatusResponse)(nil), // 6: sdk.registry.v1.SetInstanceStatusResponse
	(*HeartbeatRequest)(nil),          // 7: sdk.registry.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 8: sdk.registry.v1.HeartbeatResponse
	(*DiscoverRequest)(nil),           // 9: sdk.registry.v1.DiscoverRequest
	(*DiscoverResponse)(nil),          // 10: sdk.registry.v1.DiscoverResponse
	(*WatchRequest)(nil),              // 11: sdk.registry.v1.WatchRequest
	(*WatchResponse)(nil),             // 12: sdk.registry.v1.WatchResponse
	(*GetMembersRequest)(nil),         // 13: sdk.registry.v1.GetMembersRequest
	(*ClusterMember)(nil),             // 14: sdk.registry.v1.ClusterMember
	(*GetMembersResponse)(nil),        // 15: sdk.registry.v1.GetMembersResponse
	(*ReportTopologyRequest)(nil),     // 16: sdk.registry.v1.ReportTopologyRequest
	(*ReportTopologyResponse)(nil),    // 17: sdk.registry.v1.ReportTopologyResponse
	nil,                               // 18: sdk.registry.v1.ServiceInstance.MetadataEntry
}
var file_api_proto_registry_v1_registry_proto_depIdxs = []int32{
	18, // 0: sdk.registry.v1.ServiceInstance.metadata:type_name -> sdk.registry.v1.ServiceInstance.MetadataEntry
	0,  // 1: sdk.registry.v1.RegisterRequest.instance:type_name -> sdk.registry.v1.ServiceInstance
	0,  // 2: sdk.registry.v1.DiscoverResponse.instances:type_name -> sdk.registry.v1.ServiceInstance
	0,  // 3: sdk.registry.v1.WatchResponse.instances:type_name -> sdk.registry.v1.ServiceInstance
	14, // 4: sdk.registry.v1.GetMembersResponse.members:type_name -> sdk.registry.v1.ClusterMember
	1,  // 5: sdk.registry.v1.RegistryService.Register:input_type -> sdk.registry.v1.RegisterRequest
	3,  // 6: sdk.registry.v1.RegistryService.Deregister:input_type -> sdk.registry.v1.DeregisterRequest
	5,  // 7: sdk.registry.v1.RegistryService.SetInstanceStatus:input_type -> sdk.registry.v1.SetInstanceStatusRequest
	7,  // 8: sdk.registry.v1.RegistryService.Heartbeat:input_type -> sdk.registry.v1.HeartbeatRequest
	9,  // 9: sdk.registry.v1.RegistryService.Discover:input_type -> sdk.registry.v1.DiscoverRequest
	11, // 10: sdk.registry.v1.RegistryService.Watch:input_type -> sdk.registry.v1.WatchRequest
	13, // 11: sdk.registry.v1.RegistryService.GetMembers:input_type -> sdk.registry.v1.GetMembersRequest
	16, // 12: sdk.registry.v1.RegistryService.ReportTopology:input_type -> sdk.registry.v1.ReportTopologyRequest
	2,  // 13: sdk.registry.v1.RegistryService.Register:output_type -> sdk.registry.v1.RegisterResponse
	4,  // 14: sdk.registry.v1.RegistryService.Deregister:output_type -> sdk.registry.v1.DeregisterResponse
	6,  // 15: sdk.registry.v1.RegistryService.SetInstanceStatus:output_type -> sdk.registry.v1.SetInstanceStatusResponse
	8,  // 16: sdk.registry.v1.RegistryService.Heartbeat:output_type -> sdk.registry.v1.HeartbeatResponse
	10, // 17: sdk.registry.v1.RegistryService.Discover:output_type -> sdk.registry.v1.DiscoverResponse
	12, // 18: sdk.registry.v1.RegistryService.Watch:output_type -> sdk.registry.v1.WatchResponse
	15, // 19: sdk.registry.v1.RegistryService.GetMembers:output_type -> sdk.registry.v1.GetMembersResponse
	17, // 20: sdk.registry.v1.RegistryService.ReportTopology:output_type -> sdk.registry.v1.ReportTopologyResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_registry_v1_registry_proto_init() }
func file_api_proto_registry_v1_registry_proto_init() {
	if File_api_proto_registry_v1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_registry_v1_registry_proto_rawDesc), len(file_api_proto_registry_v1_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_registry_v1_registry_proto_goTypes,
		DependencyIndexes: file_api_proto_registry_v1_registry_proto_depIdxs,
		MessageInfos:      file_api_proto_registry_v1_registry_proto_msgTypes,
	}.Build()
	File_api_proto_registry_v1_registry_proto = out.File
	file_api_proto_registry_v1_registry_proto_goTypes = nil
	file_api_proto_registry_v1_registry_proto_depIdxs = nil
}
