// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/proto/registry/v1/registry.proto

package registryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Weight        int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Datacenter    string                 `protobuf:"bytes,7,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Namespace     string                 `protobuf:"bytes,9,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInstance) Reset() {
	*x = ServiceInstance{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInstance) ProtoMessage() {}

func (x *ServiceInstance) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInstance.ProtoReflect.Descriptor instead.
func (*ServiceInstance) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceInstance) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceInstance) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServiceInstance) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceInstance) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ServiceInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceInstance) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

func (x *ServiceInstance) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ServiceInstance) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *ServiceInstance       `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetInstance() *ServiceInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DeregisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeregisterRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *DeregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetInstanceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "online" or "offline"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInstanceStatusRequest) Reset() {
	*x = SetInstanceStatusRequest{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInstanceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInstanceStatusRequest) ProtoMessage() {}

func (x *SetInstanceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInstanceStatusRequest.ProtoReflect.Descriptor instead.
func (*SetInstanceStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *SetInstanceStatusRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SetInstanceStatusRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SetInstanceStatusRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SetInstanceStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SetInstanceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInstanceStatusResponse) Reset() {
	*x = SetInstanceStatusResponse{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInstanceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInstanceStatusResponse) ProtoMessage() {}

func (x *SetInstanceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInstanceStatusResponse.ProtoReflect.Descriptor instead.
func (*SetInstanceStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{6}
}

func (x *SetInstanceStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HeartbeatRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	HealthyOnly   bool                   `protobuf:"varint,2,opt,name=healthy_only,json=healthyOnly,proto3" json:"healthy_only,omitempty"`
	Datacenter    string                 `protobuf:"bytes,3,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{9}
}

func (x *DiscoverRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DiscoverRequest) GetHealthyOnly() bool {
	if x != nil {
		return x.HealthyOnly
	}
	return false
}

func (x *DiscoverRequest) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

func (x *DiscoverRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type DiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*ServiceInstance     `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{10}
}

func (x *DiscoverResponse) GetInstances() []*ServiceInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{11}
}

func (x *WatchRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *WatchRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "update", "offline", "online"
	Instances     []*ServiceInstance     `protobuf:"bytes,2,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_v1_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_v1_registry_proto_rawDescGZIP(), []int{12}
}

func (x *WatchResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *WatchResponse) GetInstances() []*ServiceInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

var File_api_proto_registry_v1_registry_proto protoreflect.FileDescriptor

const file_api_proto_registry_v1_registry_proto_rawDesc = "" +
	"\n" +
	"$api/proto/registry/v1/registry.proto\x12\x10eden.registry.v1\"\xe4\x02\n" +
	"\x0fServiceInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"datacenter\x18\a \x01(\tR\n" +
	"datacenter\x12K\n" +
	"\bmetadata\x18\b \x03(\v2/.eden.registry.v1.ServiceInstance.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\tnamespace\x18\t \x01(\tR\tnamespace\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x0fRegisterRequest\x12=\n" +
	"\binstance\x18\x01 \x01(\v2!.eden.registry.v1.ServiceInstanceR\binstance\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"u\n" +
	"\x11DeregisterRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\".\n" +
	"\x12DeregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x94\x01\n" +
	"\x18SetInstanceStatusRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"5\n" +
	"\x19SetInstanceStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"t\n" +
	"\x10HeartbeatRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x95\x01\n" +
	"\x0fDiscoverRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12!\n" +
	"\fhealthy_only\x18\x02 \x01(\bR\vhealthyOnly\x12\x1e\n" +
	"\n" +
	"datacenter\x18\x03 \x01(\tR\n" +
	"datacenter\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\"S\n" +
	"\x10DiscoverResponse\x12?\n" +
	"\tinstances\x18\x01 \x03(\v2!.eden.registry.v1.ServiceInstanceR\tinstances\"O\n" +
	"\fWatchRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"h\n" +
	"\rWatchResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12?\n" +
	"\tinstances\x18\x02 \x03(\v2!.eden.registry.v1.ServiceInstanceR\tinstances2\xa0\x04\n" +
	"\x0fRegistryService\x12Q\n" +
	"\bRegister\x12!.eden.registry.v1.RegisterRequest\x1a\".eden.registry.v1.RegisterResponse\x12W\n" +
	"\n" +
	"Deregister\x12#.eden.registry.v1.DeregisterRequest\x1a$.eden.registry.v1.DeregisterResponse\x12l\n" +
	"\x11SetInstanceStatus\x12*.eden.registry.v1.SetInstanceStatusRequest\x1a+.eden.registry.v1.SetInstanceStatusResponse\x12T\n" +
	"\tHeartbeat\x12\".eden.registry.v1.HeartbeatRequest\x1a#.eden.registry.v1.HeartbeatResponse\x12Q\n" +
	"\bDiscover\x12!.eden.registry.v1.DiscoverRequest\x1a\".eden.registry.v1.DiscoverResponse\x12J\n" +
	"\x05Watch\x12\x1e.eden.registry.v1.WatchRequest\x1a\x1f.eden.registry.v1.WatchResponse0\x01BNZLgithub.com/shiyindaxiaojie/eden-go-registry/api/proto/registry/v1;registryv1b\x06proto3"

var (
	file_api_proto_registry_v1_registry_proto_rawDescOnce sync.Once
	file_api_proto_registry_v1_registry_proto_rawDescData []byte
)

func file_api_proto_registry_v1_registry_proto_rawDescGZIP() []byte {
	file_api_proto_registry_v1_registry_proto_rawDescOnce.Do(func() {
		file_api_proto_registry_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_registry_v1_registry_proto_rawDesc), len(file_api_proto_registry_v1_registry_proto_rawDesc)))
	})
	return file_api_proto_registry_v1_registry_proto_rawDescData
}

var file_api_proto_registry_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_registry_v1_registry_proto_goTypes = []any{
	(*ServiceInstance)(nil),           // 0: eden.registry.v1.ServiceInstance
	(*RegisterRequest)(nil),           // 1: eden.registry.v1.RegisterRequest
	(*RegisterResponse)(nil),          // 2: eden.registry.v1.RegisterResponse
	(*DeregisterRequest)(nil),         // 3: eden.registry.v1.DeregisterRequest
	(*DeregisterResponse)(nil),        // 4: eden.registry.v1.DeregisterResponse
	(*SetInstanceStatusRequest)(nil),  // 5: eden.registry.v1.SetInstanceStatusRequest
	(*SetInstanceStatusResponse)(nil), // 6: eden.registry.v1.SetInstanceStatusResponse
	(*HeartbeatRequest)(nil),          // 7: eden.registry.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 8: eden.registry.v1.HeartbeatResponse
	(*DiscoverRequest)(nil),           // 9: eden.registry.v1.DiscoverRequest
	(*DiscoverResponse)(nil),          // 10: eden.registry.v1.DiscoverResponse
	(*WatchRequest)(nil),              // 11: eden.registry.v1.WatchRequest
	(*WatchResponse)(nil),             // 12: eden.registry.v1.WatchResponse
	nil,                               // 13: eden.registry.v1.ServiceInstance.MetadataEntry
}
var file_api_proto_registry_v1_registry_proto_depIdxs = []int32{
	13, // 0: eden.registry.v1.ServiceInstance.metadata:type_name -> eden.registry.v1.ServiceInstance.MetadataEntry
	0,  // 1: eden.registry.v1.RegisterRequest.instance:type_name -> eden.registry.v1.ServiceInstance
	0,  // 2: eden.registry.v1.DiscoverResponse.instances:type_name -> eden.registry.v1.ServiceInstance
	0,  // 3: eden.registry.v1.WatchResponse.instances:type_name -> eden.registry.v1.ServiceInstance
	1,  // 4: eden.registry.v1.RegistryService.Register:input_type -> eden.registry.v1.RegisterRequest
	3,  // 5: eden.registry.v1.RegistryService.Deregister:input_type -> eden.registry.v1.DeregisterRequest
	5,  // 6: eden.registry.v1.RegistryService.SetInstanceStatus:input_type -> eden.registry.v1.SetInstanceStatusRequest
	7,  // 7: eden.registry.v1.RegistryService.Heartbeat:input_type -> eden.registry.v1.HeartbeatRequest
	9,  // 8: eden.registry.v1.RegistryService.Discover:input_type -> eden.registry.v1.DiscoverRequest
	11, // 9: eden.registry.v1.RegistryService.Watch:input_type -> eden.registry.v1.WatchRequest
	2,  // 10: eden.registry.v1.RegistryService.Register:output_type -> eden.registry.v1.RegisterResponse
	4,  // 11: eden.registry.v1.RegistryService.Deregister:output_type -> eden.registry.v1.DeregisterResponse
	6,  // 12: eden.registry.v1.RegistryService.SetInstanceStatus:output_type -> eden.registry.v1.SetInstanceStatusResponse
	8,  // 13: eden.registry.v1.RegistryService.Heartbeat:output_type -> eden.registry.v1.HeartbeatResponse
	10, // 14: eden.registry.v1.RegistryService.Discover:output_type -> eden.registry.v1.DiscoverResponse
	12, // 15: eden.registry.v1.RegistryService.Watch:output_type -> eden.registry.v1.WatchResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_registry_v1_registry_proto_init() }
func file_api_proto_registry_v1_registry_proto_init() {
	if File_api_proto_registry_v1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_registry_v1_registry_proto_rawDesc), len(file_api_proto_registry_v1_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_registry_v1_registry_proto_goTypes,
		DependencyIndexes: file_api_proto_registry_v1_registry_proto_depIdxs,
		MessageInfos:      file_api_proto_registry_v1_registry_proto_msgTypes,
	}.Build()
	File_api_proto_registry_v1_registry_proto = out.File
	file_api_proto_registry_v1_registry_proto_goTypes = nil
	file_api_proto_registry_v1_registry_proto_depIdxs = nil
}
