// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/proto/cluster/v1/cluster.proto

package clusterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncSeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seeds         []string               `protobuf:"bytes,1,rep,name=seeds,proto3" json:"seeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSeedsRequest) Reset() {
	*x = SyncSeedsRequest{}
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSeedsRequest) ProtoMessage() {}

func (x *SyncSeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSeedsRequest.ProtoReflect.Descriptor instead.
func (*SyncSeedsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *SyncSeedsRequest) GetSeeds() []string {
	if x != nil {
		return x.Seeds
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SyncUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	IsBuiltIn     bool                   `protobuf:"varint,6,opt,name=is_built_in,json=isBuiltIn,proto3" json:"is_built_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserRequest) Reset() {
	*x = SyncUserRequest{}
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserRequest) ProtoMessage() {}

func (x *SyncUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserRequest.ProtoReflect.Descriptor instead.
func (*SyncUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *SyncUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SyncUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SyncUserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *SyncUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SyncUserRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *SyncUserRequest) GetIsBuiltIn() bool {
	if x != nil {
		return x.IsBuiltIn
	}
	return false
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SyncAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAPIKeyRequest) Reset() {
	*x = SyncAPIKeyRequest{}
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAPIKeyRequest) ProtoMessage() {}

func (x *SyncAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*SyncAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *SyncAPIKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SyncAPIKeyRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SyncAPIKeyRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SyncAPIKeyRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type DeleteAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAPIKeyRequest) Reset() {
	*x = DeleteAPIKeyRequest{}
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPIKeyRequest) ProtoMessage() {}

func (x *DeleteAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAPIKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SyncSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	LogLevel      string                 `protobuf:"bytes,3,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSettingsRequest) Reset() {
	*x = SyncSettingsRequest{}
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSettingsRequest) ProtoMessage() {}

func (x *SyncSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSettingsRequest.ProtoReflect.Descriptor instead.
func (*SyncSettingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *SyncSettingsRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SyncSettingsRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *SyncSettingsRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

type ReplicateLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandType   string                 `protobuf:"bytes,1,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateLogRequest) Reset() {
	*x = ReplicateLogRequest{}
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateLogRequest) ProtoMessage() {}

func (x *ReplicateLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateLogRequest.ProtoReflect.Descriptor instead.
func (*ReplicateLogRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *ReplicateLogRequest) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *ReplicateLogRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *ForwardRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ForwardRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ForwardRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type ForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_v1_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_v1_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *ForwardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ForwardResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_api_proto_cluster_v1_cluster_proto protoreflect.FileDescriptor

const file_api_proto_cluster_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/cluster/v1/cluster.proto\x12\x0feden.cluster.v1\"(\n" +
	"\x10SyncSeedsRequest\x12\x14\n" +
	"\x05seeds\x18\x01 \x03(\tR\x05seeds\"B\n" +
	"\fSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb1\x01\n" +
	"\x0fSyncUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x1e\n" +
	"\vis_built_in\x18\x06 \x01(\bR\tisBuiltIn\"/\n" +
	"\x11DeleteUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"y\n" +
	"\x11SyncAPIKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"'\n" +
	"\x13DeleteAPIKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"K\n" +
	"\x13SyncSettingsRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12 \n" +
	"\venvironment\x18\x02 \x01(\tR\venvironment\"L\n" +
	"\x13ReplicateLogRequest\x12!\n" +
	"\fcommand_type\x18\x01 \x01(\tR\vcommandType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"P\n" +
	"\x0eForwardRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\"`\n" +
	"\x0fForwardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body2\xa3\x05\n" +
	"\x0eClusterService\x12M\n" +
	"\tSyncSeeds\x12!.eden.cluster.v1.SyncSeedsRequest\x1a\x1d.eden.cluster.v1.SyncResponse\x12K\n" +
	"\bSyncUser\x12 .eden.cluster.v1.SyncUserRequest\x1a\x1d.eden.cluster.v1.SyncResponse\x12O\n" +
	"\n" +
	"DeleteUser\x12\".eden.cluster.v1.DeleteUserRequest\x1a\x1d.eden.cluster.v1.SyncResponse\x12O\n" +
	"\n" +
	"SyncAPIKey\x12\".eden.cluster.v1.SyncAPIKeyRequest\x1a\x1d.eden.cluster.v1.SyncResponse\x12S\n" +
	"\fDeleteAPIKey\x12$.eden.cluster.v1.DeleteAPIKeyRequest\x1a\x1d.eden.cluster.v1.SyncResponse\x12S\n" +
	"\fSyncSettings\x12$.eden.cluster.v1.SyncSettingsRequest\x1a\x1d.eden.cluster.v1.SyncResponse\x12S\n" +
	"\fReplicateLog\x12$.eden.cluster.v1.ReplicateLogRequest\x1a\x1d.eden.cluster.v1.SyncResponse\x12T\n" +
	"\x0fForwardToLeader\x12\x1f.eden.cluster.v1.ForwardRequest\x1a .eden.cluster.v1.ForwardResponseBLZJgithub.com/shiyindaxiaojie/eden-go-registry/api/proto/cluster/v1;clusterv1b\x06proto3"

var (
	file_api_proto_cluster_v1_cluster_proto_rawDescOnce sync.Once
	file_api_proto_cluster_v1_cluster_proto_rawDescData []byte
)

func file_api_proto_cluster_v1_cluster_proto_rawDescGZIP() []byte {
	file_api_proto_cluster_v1_cluster_proto_rawDescOnce.Do(func() {
		file_api_proto_cluster_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cluster_v1_cluster_proto_rawDesc), len(file_api_proto_cluster_v1_cluster_proto_rawDesc)))
	})
	return file_api_proto_cluster_v1_cluster_proto_rawDescData
}

var file_api_proto_cluster_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_cluster_v1_cluster_proto_goTypes = []any{
	(*SyncSeedsRequest)(nil),    // 0: eden.cluster.v1.SyncSeedsRequest
	(*SyncResponse)(nil),        // 1: eden.cluster.v1.SyncResponse
	(*SyncUserRequest)(nil),     // 2: eden.cluster.v1.SyncUserRequest
	(*DeleteUserRequest)(nil),   // 3: eden.cluster.v1.DeleteUserRequest
	(*SyncAPIKeyRequest)(nil),   // 4: eden.cluster.v1.SyncAPIKeyRequest
	(*DeleteAPIKeyRequest)(nil), // 5: eden.cluster.v1.DeleteAPIKeyRequest
	(*SyncSettingsRequest)(nil), // 6: eden.cluster.v1.SyncSettingsRequest
	(*ReplicateLogRequest)(nil), // 7: eden.cluster.v1.ReplicateLogRequest
	(*ForwardRequest)(nil),      // 8: eden.cluster.v1.ForwardRequest
	(*ForwardResponse)(nil),     // 9: eden.cluster.v1.ForwardResponse
}
var file_api_proto_cluster_v1_cluster_proto_depIdxs = []int32{
	0, // 0: eden.cluster.v1.ClusterService.SyncSeeds:input_type -> eden.cluster.v1.SyncSeedsRequest
	2, // 1: eden.cluster.v1.ClusterService.SyncUser:input_type -> eden.cluster.v1.SyncUserRequest
	3, // 2: eden.cluster.v1.ClusterService.DeleteUser:input_type -> eden.cluster.v1.DeleteUserRequest
	4, // 3: eden.cluster.v1.ClusterService.SyncAPIKey:input_type -> eden.cluster.v1.SyncAPIKeyRequest
	5, // 4: eden.cluster.v1.ClusterService.DeleteAPIKey:input_type -> eden.cluster.v1.DeleteAPIKeyRequest
	6, // 5: eden.cluster.v1.ClusterService.SyncSettings:input_type -> eden.cluster.v1.SyncSettingsRequest
	7, // 6: eden.cluster.v1.ClusterService.ReplicateLog:input_type -> eden.cluster.v1.ReplicateLogRequest
	8, // 7: eden.cluster.v1.ClusterService.ForwardToLeader:input_type -> eden.cluster.v1.ForwardRequest
	1, // 8: eden.cluster.v1.ClusterService.SyncSeeds:output_type -> eden.cluster.v1.SyncResponse
	1, // 9: eden.cluster.v1.ClusterService.SyncUser:output_type -> eden.cluster.v1.SyncResponse
	1, // 10: eden.cluster.v1.ClusterService.DeleteUser:output_type -> eden.cluster.v1.SyncResponse
	1, // 11: eden.cluster.v1.ClusterService.SyncAPIKey:output_type -> eden.cluster.v1.SyncResponse
	1, // 12: eden.cluster.v1.ClusterService.DeleteAPIKey:output_type -> eden.cluster.v1.SyncResponse
	1, // 13: eden.cluster.v1.ClusterService.SyncSettings:output_type -> eden.cluster.v1.SyncResponse
	1, // 14: eden.cluster.v1.ClusterService.ReplicateLog:output_type -> eden.cluster.v1.SyncResponse
	9, // 15: eden.cluster.v1.ClusterService.ForwardToLeader:output_type -> eden.cluster.v1.ForwardResponse
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_cluster_v1_cluster_proto_init() }
func file_api_proto_cluster_v1_cluster_proto_init() {
	if File_api_proto_cluster_v1_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cluster_v1_cluster_proto_rawDesc), len(file_api_proto_cluster_v1_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cluster_v1_cluster_proto_goTypes,
		DependencyIndexes: file_api_proto_cluster_v1_cluster_proto_depIdxs,
		MessageInfos:      file_api_proto_cluster_v1_cluster_proto_msgTypes,
	}.Build()
	File_api_proto_cluster_v1_cluster_proto = out.File
	file_api_proto_cluster_v1_cluster_proto_goTypes = nil
	file_api_proto_cluster_v1_cluster_proto_depIdxs = nil
}
