// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: api/proto/cluster/v1/cluster.proto

package clusterv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterService_SyncSeeds_FullMethodName       = "/eden.cluster.v1.ClusterService/SyncSeeds"
	ClusterService_SyncUser_FullMethodName        = "/eden.cluster.v1.ClusterService/SyncUser"
	ClusterService_DeleteUser_FullMethodName      = "/eden.cluster.v1.ClusterService/DeleteUser"
	ClusterService_SyncAPIKey_FullMethodName      = "/eden.cluster.v1.ClusterService/SyncAPIKey"
	ClusterService_DeleteAPIKey_FullMethodName    = "/eden.cluster.v1.ClusterService/DeleteAPIKey"
	ClusterService_SyncSettings_FullMethodName    = "/eden.cluster.v1.ClusterService/SyncSettings"
	ClusterService_ReplicateLog_FullMethodName    = "/eden.cluster.v1.ClusterService/ReplicateLog"
	ClusterService_SyncDiscovery_FullMethodName   = "/eden.cluster.v1.ClusterService/SyncDiscovery"
	ClusterService_ForwardToLeader_FullMethodName = "/eden.cluster.v1.ClusterService/ForwardToLeader"
)

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClusterService defines the gRPC API for node-to-node communication.
type ClusterServiceClient interface {
	// Sync seeds (node list) to a peer.
	SyncSeeds(ctx context.Context, in *SyncSeedsRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Sync a user to a peer.
	SyncUser(ctx context.Context, in *SyncUserRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Delete a user on a peer.
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Sync an API key to a peer.
	SyncAPIKey(ctx context.Context, in *SyncAPIKeyRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Delete an API key on a peer.
	DeleteAPIKey(ctx context.Context, in *DeleteAPIKeyRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Sync settings (mode, environment) to a peer.
	SyncSettings(ctx context.Context, in *SyncSettingsRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Replicate a log entry (for AP mode broadcast).
	ReplicateLog(ctx context.Context, in *ReplicateLogRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Pull full discovery state from a peer (Anti-Entropy).
	SyncDiscovery(ctx context.Context, in *SyncDiscoveryRequest, opts ...grpc.CallOption) (*SyncDiscoveryResponse, error)
	// Forward a write request to the leader (for CP mode).
	ForwardToLeader(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error)
}

type clusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterServiceClient(cc grpc.ClientConnInterface) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) SyncSeeds(ctx context.Context, in *SyncSeedsRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, ClusterService_SyncSeeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) SyncUser(ctx context.Context, in *SyncUserRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, ClusterService_SyncUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, ClusterService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) SyncAPIKey(ctx context.Context, in *SyncAPIKeyRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, ClusterService_SyncAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) DeleteAPIKey(ctx context.Context, in *DeleteAPIKeyRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, ClusterService_DeleteAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) SyncSettings(ctx context.Context, in *SyncSettingsRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, ClusterService_SyncSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) ReplicateLog(ctx context.Context, in *ReplicateLogRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, ClusterService_ReplicateLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) SyncDiscovery(ctx context.Context, in *SyncDiscoveryRequest, opts ...grpc.CallOption) (*SyncDiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncDiscoveryResponse)
	err := c.cc.Invoke(ctx, ClusterService_SyncDiscovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) ForwardToLeader(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardResponse)
	err := c.cc.Invoke(ctx, ClusterService_ForwardToLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServiceServer is the server API for ClusterService service.
// All implementations must embed UnimplementedClusterServiceServer
// for forward compatibility.
//
// ClusterService defines the gRPC API for node-to-node communication.
type ClusterServiceServer interface {
	// Sync seeds (node list) to a peer.
	SyncSeeds(context.Context, *SyncSeedsRequest) (*SyncResponse, error)
	// Sync a user to a peer.
	SyncUser(context.Context, *SyncUserRequest) (*SyncResponse, error)
	// Delete a user on a peer.
	DeleteUser(context.Context, *DeleteUserRequest) (*SyncResponse, error)
	// Sync an API key to a peer.
	SyncAPIKey(context.Context, *SyncAPIKeyRequest) (*SyncResponse, error)
	// Delete an API key on a peer.
	DeleteAPIKey(context.Context, *DeleteAPIKeyRequest) (*SyncResponse, error)
	// Sync settings (mode, environment) to a peer.
	SyncSettings(context.Context, *SyncSettingsRequest) (*SyncResponse, error)
	// Replicate a log entry (for AP mode broadcast).
	ReplicateLog(context.Context, *ReplicateLogRequest) (*SyncResponse, error)
	// Pull full discovery state from a peer (Anti-Entropy).
	SyncDiscovery(context.Context, *SyncDiscoveryRequest) (*SyncDiscoveryResponse, error)
	// Forward a write request to the leader (for CP mode).
	ForwardToLeader(context.Context, *ForwardRequest) (*ForwardResponse, error)
	mustEmbedUnimplementedClusterServiceServer()
}

// UnimplementedClusterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterServiceServer struct{}

func (UnimplementedClusterServiceServer) SyncSeeds(context.Context, *SyncSeedsRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncSeeds not implemented")
}
func (UnimplementedClusterServiceServer) SyncUser(context.Context, *SyncUserRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncUser not implemented")
}
func (UnimplementedClusterServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedClusterServiceServer) SyncAPIKey(context.Context, *SyncAPIKeyRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncAPIKey not implemented")
}
func (UnimplementedClusterServiceServer) DeleteAPIKey(context.Context, *DeleteAPIKeyRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAPIKey not implemented")
}
func (UnimplementedClusterServiceServer) SyncSettings(context.Context, *SyncSettingsRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncSettings not implemented")
}
func (UnimplementedClusterServiceServer) ReplicateLog(context.Context, *ReplicateLogRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateLog not implemented")
}
func (UnimplementedClusterServiceServer) SyncDiscovery(context.Context, *SyncDiscoveryRequest) (*SyncDiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncDiscovery not implemented")
}
func (UnimplementedClusterServiceServer) ForwardToLeader(context.Context, *ForwardRequest) (*ForwardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardToLeader not implemented")
}
func (UnimplementedClusterServiceServer) mustEmbedUnimplementedClusterServiceServer() {}
func (UnimplementedClusterServiceServer) testEmbeddedByValue()                        {}

// UnsafeClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServiceServer will
// result in compilation errors.
type UnsafeClusterServiceServer interface {
	mustEmbedUnimplementedClusterServiceServer()
}

func RegisterClusterServiceServer(s grpc.ServiceRegistrar, srv ClusterServiceServer) {
	// If the following call panics, it indicates UnimplementedClusterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterService_ServiceDesc, srv)
}

func _ClusterService_SyncSeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncSeedsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).SyncSeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_SyncSeeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).SyncSeeds(ctx, req.(*SyncSeedsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_SyncUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).SyncUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_SyncUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).SyncUser(ctx, req.(*SyncUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_SyncAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).SyncAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_SyncAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).SyncAPIKey(ctx, req.(*SyncAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_DeleteAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).DeleteAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_DeleteAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).DeleteAPIKey(ctx, req.(*DeleteAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_SyncSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).SyncSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_SyncSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).SyncSettings(ctx, req.(*SyncSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_ReplicateLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).ReplicateLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_ReplicateLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).ReplicateLog(ctx, req.(*ReplicateLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_SyncDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncDiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).SyncDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_SyncDiscovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).SyncDiscovery(ctx, req.(*SyncDiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_ForwardToLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).ForwardToLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_ForwardToLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).ForwardToLeader(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterService_ServiceDesc is the grpc.ServiceDesc for ClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eden.cluster.v1.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncSeeds",
			Handler:    _ClusterService_SyncSeeds_Handler,
		},
		{
			MethodName: "SyncUser",
			Handler:    _ClusterService_SyncUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _ClusterService_DeleteUser_Handler,
		},
		{
			MethodName: "SyncAPIKey",
			Handler:    _ClusterService_SyncAPIKey_Handler,
		},
		{
			MethodName: "DeleteAPIKey",
			Handler:    _ClusterService_DeleteAPIKey_Handler,
		},
		{
			MethodName: "SyncSettings",
			Handler:    _ClusterService_SyncSettings_Handler,
		},
		{
			MethodName: "ReplicateLog",
			Handler:    _ClusterService_ReplicateLog_Handler,
		},
		{
			MethodName: "SyncDiscovery",
			Handler:    _ClusterService_SyncDiscovery_Handler,
		},
		{
			MethodName: "ForwardToLeader",
			Handler:    _ClusterService_ForwardToLeader_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/cluster/v1/cluster.proto",
}
